//! Generates `packages/types/bindings.ts` from all #[specta::specta] commands.
//! Run via: bun run codegen  (i.e. `cargo run -p codegen` from the repo root).
fn main() {
    voleeo_lib::specta_builder()
        .export(
            specta_typescript::Typescript::default()
                .header("// This file is auto-generated by tauri-specta. Do not edit manually.\n// Run: bun run codegen\n// @ts-nocheck"),
            "packages/types/bindings.ts",
        )
        .expect("codegen failed");
}
