import type { Icon, IconProps } from "@phosphor-icons/react"
import {
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowsClockwiseIcon,
  ArrowsLeftRightIcon,
  ArrowUpIcon,
  BookOpenTextIcon,
  CalendarBlankIcon,
  CaretDoubleLeftIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretRightIcon,
  CheckIcon,
  ChecksIcon,
  ClockCounterClockwiseIcon,
  ClockIcon,
  CodeIcon,
  ColumnsIcon,
  CookieIcon,
  CopyIcon,
  DotsSixVerticalIcon,
  DotsThreeVerticalIcon,
  DownloadSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FileIcon,
  FileSqlIcon,
  FloppyDiskIcon,
  FolderIcon,
  FunnelIcon,
  FunnelSimpleIcon,
  GearIcon,
  GitBranchIcon,
  GitCommitIcon,
  GlobeIcon,
  HardDriveIcon,
  InfoIcon,
  KeyboardIcon,
  KeyIcon,
  LightningIcon,
  LightningSlashIcon,
  LinkBreakIcon,
  LinkIcon,
  ListIcon,
  LockIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  PaperPlaneRightIcon,
  PaperPlaneTiltIcon,
  PencilSimpleIcon,
  PlayIcon,
  PlugChargingIcon,
  PlugsConnectedIcon,
  PlugsIcon,
  PlusIcon,
  RowsIcon,
  ShieldCheckIcon,
  ShieldSlashIcon,
  ShieldStarIcon,
  SidebarSimpleIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SparkleIcon,
  SquaresFourIcon,
  TableIcon,
  TerminalIcon,
  TrashIcon,
  TreeStructureIcon,
  UploadSimpleIcon,
  WarningIcon,
  WarningOctagonIcon,
  XIcon,
} from "@phosphor-icons/react"
import type { CSSProperties } from "react"

interface GlyphProps {
  kind: string
  size?: number
  color?: string
  style?: CSSProperties
}

const KIND_MAP: Record<string, Icon> = {
  api: GlobeIcon,
  book: BookOpenTextIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  search: MagnifyingGlassIcon,
  filter: FunnelIcon,
  "funnel-simple": FunnelSimpleIcon,
  "sort-ascending": SortAscendingIcon,
  "sort-descending": SortDescendingIcon,
  folder: FolderIcon,
  bridge: PlugsIcon,
  plugs: PlugsIcon,
  "plugs-connected": PlugsConnectedIcon,
  "plug-charging": PlugChargingIcon,
  lightning: LightningIcon,
  "lightning-slash": LightningSlashIcon,
  calendar: CalendarBlankIcon,
  check: CheckIcon,
  checks: ChecksIcon,
  chevron: CaretRightIcon,
  "chevron-down": CaretDownIcon,
  "chevrons-left": CaretDoubleLeftIcon,
  "chevrons-right": CaretDoubleRightIcon,
  arrow: ArrowRightIcon,
  "arrow-left": ArrowLeftIcon,
  "arrows-left-right": ArrowsLeftRightIcon,
  import: DownloadSimpleIcon,
  grid: SquaresFourIcon,
  list: ListIcon,
  terminal: TerminalIcon,
  x: XIcon,
  play: PlayIcon,
  save: FloppyDiskIcon,
  send: PaperPlaneTiltIcon,
  "send-right": PaperPlaneRightIcon,
  history: ClockCounterClockwiseIcon,
  clock: ClockIcon,
  table: TableIcon,
  schema: TreeStructureIcon,
  sparkle: SparkleIcon,
  server: HardDriveIcon,
  columns: ColumnsIcon,
  rows: RowsIcon,
  refresh: ArrowsClockwiseIcon,
  "arrows-clockwise": ArrowsClockwiseIcon,
  "arrow-counter-clockwise": ArrowCounterClockwiseIcon,
  "arrow-down": ArrowDownIcon,
  upload: ArrowUpIcon,
  "upload-simple": UploadSimpleIcon,
  link: LinkIcon,
  settings: GearIcon,
  commit: GitCommitIcon,
  branch: GitBranchIcon,
  view: EyeIcon,
  hide: EyeSlashIcon,
  info: InfoIcon,
  keyboard: KeyboardIcon,
  disconnect: LinkBreakIcon,
  query: FileSqlIcon,
  key: KeyIcon,
  lock: LockIcon,
  "shield-star": ShieldStarIcon,
  "shield-slash": ShieldSlashIcon,
  "shield-check": ShieldCheckIcon,
  copy: CopyIcon,
  edit: PencilSimpleIcon,
  warning: WarningIcon,
  "warning-octagon": WarningOctagonIcon,
  globe: GlobeIcon,
  cookie: CookieIcon,
  code: CodeIcon,
  file: FileIcon,
  trash: TrashIcon,
  "drag-handle": DotsSixVerticalIcon,
  more: DotsThreeVerticalIcon,
  wand: MagicWandIcon,
  index: SortAscendingIcon,
  sidebar: SidebarSimpleIcon,
}

export function Glyph({
  kind,
  size = 16,
  color = "var(--base04)",
  style,
}: GlyphProps) {
  const IconComponent = KIND_MAP[kind]
  const props: IconProps = { size, color, weight: "light", style }
  return IconComponent ? (
    <IconComponent {...props} />
  ) : (
    <ArrowsLeftRightIcon {...props} />
  )
}
